"""Report generation service — JSON and PDF export."""

import os
from typing import Optional

import structlog
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.report import Report, ReportFormat
from app.models.simulation import Simulation

logger = structlog.get_logger(__name__)
UPLOAD_DIR = os.environ.get("UPLOAD_DIR", "/app/uploads")


class ReportService:
    def __init__(self, db: AsyncSession) -> None:
        self.db = db

    async def generate_json_report(self, simulation: Simulation) -> Report:
        """Generate a structured JSON report from simulation results."""
        from app.repositories.agent_output_repository import AgentOutputRepository

        agent_repo = AgentOutputRepository(self.db)
        outputs = await agent_repo.get_by_simulation(simulation.id)

        consensus = simulation.consensus or {}

        key_findings = []
        for output in outputs:
            if output.summary:
                key_findings.append({
                    "domain": output.agent_role,
                    "finding": output.summary,
                    "confidence": output.confidence,
                })

        recommendations = [
            {"action": rec, "priority": "high" if i < 3 else "medium"}
            for i, rec in enumerate(consensus.get("recommended_actions", []))
        ]

        risk_assessment = {
            "level": consensus.get("risk_level", "medium"),
            "key_uncertainties": consensus.get("key_uncertainties", []),
            "conflicts": consensus.get("conflicts", []),
        }

        confidence_overview = {
            "overall": consensus.get("overall_confidence", 0.0),
            "by_agent": {
                o.agent_role: o.confidence
                for o in outputs
                if o.confidence is not None
            },
        }

        report = Report(
            simulation_id=simulation.id,
            title=f"Executive Report: {simulation.title}",
            format=ReportFormat.JSON,
            executive_summary=consensus.get("overall_summary", ""),
            key_findings=key_findings,
            recommendations=recommendations,
            risk_assessment=risk_assessment,
            confidence_overview=confidence_overview,
            methodology=(
                "This report was generated by the Nexus AI Multi-Agent Decision Intelligence Platform. "
                "Five specialized AI agents (Economist, Policy Analyst, Technology Strategist, "
                "Environmental Scientist, Supply Chain Expert) independently analyzed the decision, "
                "followed by consensus synthesis and causal graph construction."
            ),
        )
        self.db.add(report)
        await self.db.flush()
        await self.db.refresh(report)
        return report

    async def export_pdf(self, report: Report) -> str:
        """Generate a PDF from the report and return its file path."""
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import inch
        from reportlab.platypus import (
            HRFlowable,
            PageBreak,
            Paragraph,
            SimpleDocTemplate,
            Spacer,
            Table,
            TableStyle,
        )

        os.makedirs(UPLOAD_DIR, exist_ok=True)
        pdf_path = os.path.join(UPLOAD_DIR, f"report_{report.id}.pdf")

        doc = SimpleDocTemplate(
            pdf_path,
            pagesize=A4,
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=1 * inch,
            bottomMargin=1 * inch,
        )

        styles = getSampleStyleSheet()
        accent_color = colors.HexColor("#00D9FF")
        dark_bg = colors.HexColor("#111111")

        title_style = ParagraphStyle(
            "Title",
            parent=styles["Title"],
            fontSize=24,
            textColor=accent_color,
            spaceAfter=6,
        )
        h2_style = ParagraphStyle(
            "H2",
            parent=styles["Heading2"],
            fontSize=14,
            textColor=accent_color,
            spaceBefore=16,
            spaceAfter=6,
        )
        body_style = ParagraphStyle(
            "Body",
            parent=styles["Normal"],
            fontSize=10,
            leading=14,
            spaceAfter=4,
        )

        story = []
        story.append(Paragraph("NEXUS AI", title_style))
        story.append(Paragraph(report.title, styles["Heading1"]))
        story.append(HRFlowable(width="100%", thickness=1, color=accent_color))
        story.append(Spacer(1, 0.2 * inch))

        # Executive Summary
        story.append(Paragraph("Executive Summary", h2_style))
        story.append(Paragraph(report.executive_summary or "No summary available.", body_style))
        story.append(Spacer(1, 0.1 * inch))

        # Key Findings
        if report.key_findings:
            story.append(Paragraph("Key Findings", h2_style))
            for f in report.key_findings:
                domain = f.get("domain", "").upper()
                conf = f.get("confidence", 0)
                finding = f.get("finding", "")
                story.append(Paragraph(f"<b>[{domain}]</b> (Confidence: {conf:.0%}): {finding}", body_style))
            story.append(Spacer(1, 0.1 * inch))

        # Recommendations
        if report.recommendations:
            story.append(Paragraph("Recommendations", h2_style))
            for i, r in enumerate(report.recommendations, 1):
                story.append(Paragraph(f"{i}. {r.get('action', '')}", body_style))
            story.append(Spacer(1, 0.1 * inch))

        # Risk Assessment
        if report.risk_assessment:
            story.append(Paragraph("Risk Assessment", h2_style))
            risk = report.risk_assessment
            story.append(Paragraph(f"<b>Risk Level:</b> {risk.get('level', 'N/A').upper()}", body_style))
            for u in risk.get("key_uncertainties", []):
                story.append(Paragraph(f"• {u}", body_style))

        # Methodology
        if report.methodology:
            story.append(PageBreak())
            story.append(Paragraph("Methodology", h2_style))
            story.append(Paragraph(report.methodology, body_style))

        story.append(Spacer(1, 0.3 * inch))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
        story.append(Paragraph("Generated by Nexus AI — Simulate Decisions Before Reality Does.", body_style))

        doc.build(story)

        # Update report with file path
        report.file_path = pdf_path
        await self.db.flush()

        logger.info("PDF report generated", report_id=report.id, path=pdf_path)
        return pdf_path
